spring.config.import=optional:file:env/.env.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/telegramBot
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
app.notifications.cron=0 * * * * *
app.notifications.zone=Europe/Moscow
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.liquibase=WARN
logging.level.pro.sky.telegrambot=INFO