-- liquibase formatted sql

-- changeset OATimofeev:1
CREATE TABLE notification_task (
                                   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                   chat_id BIGINT NOT NULL,
                                   message VARCHAR(1000) NOT NULL,
                                   send_at TIMESTAMP NOT NULL,
                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   sent BOOLEAN NOT NULL DEFAULT FALSE
);

-- changeset OATimofeev:2
CREATE INDEX notification_task_send_at_idx
    ON notification_task (send_at);

-- changeset OATimofeev:3
CREATE INDEX notification_task_sent_send_at_idx
    ON notification_task (sent, send_at);